// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsB0b0q9r6zgCzEBOMCJ2IqOahTxaqufI',
    appId: '1:1046550965009:android:4e33ae859ab84c7ea6bab0',
    messagingSenderId: '1046550965009',
    projectId: 'kanban-fire-8b66b',
    databaseURL: 'https://kanban-fire-8b66b-default-rtdb.firebaseio.com',
    storageBucket: 'kanban-fire-8b66b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj9S6JCW7T1ywm6ieKLeqJB_1-bBXvY3Y',
    appId: '1:1046550965009:ios:245ab2a3bb9d3b9fa6bab0',
    messagingSenderId: '1046550965009',
    projectId: 'kanban-fire-8b66b',
    databaseURL: 'https://kanban-fire-8b66b-default-rtdb.firebaseio.com',
    storageBucket: 'kanban-fire-8b66b.appspot.com',
    iosClientId: '1046550965009-ic6p4tmggcv8dc2lcac53i7si04c46re.apps.googleusercontent.com',
    iosBundleId: 'com.example.chennaiCabsDev',
  );
}
